# data
train_data_dir: ['../dgrl_train']
eval_data_dir: ['../dgrl_test']
train_batch_size: 1
eval_batch_size: 1
num_workers: 8
# model
num_classes: 3000
line_height: 32
# train
epochs: 50
lr: 0.0001
# print
display_interval: 20
print_pred: 200
